# Generated by Django 4.2.4 on 2023-09-13 23:52

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddle',
            name='num_accesed',
            field=banjo.models.IntegerField(default=0),
        ),
    ]
