# Generated by Django 5.1 on 2024-08-29 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_riddle_num_accesed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riddle',
            name='num_accesed',
        ),
    ]
